src/FotoCuadro/PedidoBundle/Entity/Producto.php
<?php

namespace FotoCuadro\PedidoBundle\Entity;
use FotoCuadro\GaleriaBundle\Entity\Foto;
use Symfony\Component\Validator\Constraints\DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints as DoctrineAssert;
use FotoCuadro\UsuarioBundle\Lib\Util\Util;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Doctrine\ORM\Mapping\Index;

/**
 * Entidad RolClub de FotoCuadro
 * @ORM\Table(name="producto") 
 * @ORM\Entity
 */
class Producto {

	/**
	 * Pedido al que pertence el producto
	 * @ORM\Id
	 * @ORM\ManyToOne(targetEntity="FotoCuadro\PedidoBundle\Entity\Pedido")
	 * @ORM\JoinColumn(name="pedido", referencedColumnName="id", onDelete="CASCADE", onUpdate="CASCADE")
	 */ 
	protected $pedido;
	/**
	 * Foto que se ha pedido
	 * @ORM\Id
	 * @ORM\ManyToOne(targetEntity="FotoCuadro\GaleriaBundle\Entity\Foto")
	 * @ORM\JoinColumn(name="foto", referencedColumnName="id", onDelete="CASCADE", onUpdate="CASCADE")
	 */
	protected $foto;
	/**
	 * Tipo de producto seleccionado para la foto
	 * @ORM\Id
	 * @ORM\ManyToOne(targetEntity="FotoCuadro\PedidoBundle\Entity\TipoProducto")
	 * @ORM\JoinColumn(name="tipo_producto", referencedColumnName="id", onDelete="CASCADE", onUpdate="CASCADE")
	 */
	protected $tipo_producto;
	/**
	 * Cantidad pedida 
	 * @ORM\Column(type="integer", nullable=false)
	 */
	protected $cantidad;

	/**
	 * Constructor de la clase. Inicia los valores por defecto
	 */
	public function __construct() {
		$this->cantidad = 0;
	}
	/**
	 * Getter para el pedido
	 * @return Pedido
	 */
	public function getPedido() {
		return $this->pedido;
	}
	/**
	 * Setter para el pedido
	 * @param Pedido $pedido
	 */
	public function setPedido(Pedido $pedido) {
		$this->pedido = $pedido;
	}
	/**
	 * Getter para la foto del pedido
	 * @return Foto
	 */
	public function getFoto() {
		return $this->foto;
	}
	/**
	 * Setter para la foto del pedido
	 * @param Foto $foto
	 */
	public function setFoto(Foto $foto) {
		$this->foto = $foto;
	}
	/**
	 * Getter para el tipo de producto
	 * @return TipoProducto
	 */
	public function getTipoProducto() {
		return $this->tipo_producto;
	}
	/**
	 * Setter para el tipo de producto
	 * @param TipoProducto $tipo_producto
	 */
	public function setTipoProducto($tipo_producto) {
		$this->tipo_producto = $tipo_producto;
	}
	/**
	 * Getter para la cantidad pedida para el producto
	 * @return int
	 */
	public function getCantidad() {
		return $this->cantidad;
	}
	/**
	 * Setter para la cantidad pedida para el producto
	 * @param int $cantidad
	 */
	public function setCantidad($cantidad) {
		$this->cantidad = $cantidad;
	}

}

src/FotoCuadro/PedidoBundle/Controller/DefaultController.php
<?php


namespace FotoCuadro\PedidoBundle\Controller;

use FotoCuadro\UsuarioBundle\Form\ClienteType;

use FotoCuadro\UsuarioBundle\Entity\Cliente;

use FotoCuadro\PedidoBundle\Entity\Producto;

use FotoCuadro\UsuarioBundle\Lib\Util\Util;

use FotoCuadro\PedidoBundle\Form\PedidoType;

use FotoCuadro\PedidoBundle\Entity\Pedido;
use FotoCuadro\UsuarioBundle\Entity\Usuario;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;


class DefaultController extends Controller
{
	/**
	 * Acción para el index de pedidos con el listado de pedidos y el boton
	 */
    public function indexAction()
    {    	    	
    	// cojo los datos del usuario
    	$user = $this->get('security.context')->getToken()->getUser();
    	// obtener listado de pedidos
    	$em = $this->getDoctrine()->getEntityManager();
    	$pedidos = $em->getRepository('PedidoBundle:Pedido')->findPedidosByUser($user);    	
    	
    	return $this->render('PedidoBundle:Default:index.html.twig',
    			array(    					
    					'pedidos' => $pedidos, 
    					'estados' => Pedido::getEstados(),   					
    			));    	
    }
    
    /**
     * Acción para editar un pedido
     * @param integer $id
     */
    public function editAction($id)
    {
    	$em = $this->getDoctrine()->getEntityManager();
    	//recupero la informacion del pedido a editar
    	$entity = $em->getRepository('PedidoBundle:Pedido')->findPedidoById($id);
    	if (!$entity) {
    		throw $this->createNotFoundException('No se ha podido encontrar el pedido.');
    	}
    	// creo el formulario de edición
    	//$editForm = $this->createForm(new PedidoType(), $entity);
    	// muestro el formulario
    	return $this->render('PedidoBundle:Default:edit.html.twig',
    			array(
    					'estados' => Pedido::getEstados(),
    					'entity' => $entity,
    			));
    
    }
    
    /**
     * Acción para el primer paso del pedido, mostrar la selección de clubes
     */
    public function newClubesAction()
    {    	
    	// cojo los datos del usuario
    	$user = $this->get('security.context')->getToken()->getUser();
    	// obtener listado de equipos
    	$em = $this->getDoctrine()->getEntityManager();
    	if ($user->getRol() == Usuario::ROL_ADMIN)
    		$lista = $em->getRepository('ClubBundle:Club')->findAllClubes();
    	else
    		$lista = $em->getRepository('ClubBundle:Club')->findClubesByUser($user->getId());
    	
    	// creo el pedido    			  
    	$pedido = array(
    			'id' => null,
    			'fecha' => new \DateTime(),
    			'usuario' => $user->getId(),
    			'cliente' => null,
    			'importe' => 0.00,
    			'pagado' => 0.00,
    			'estado' => Pedido::PEDIDO_PENDIENTE,
    			'incidencias' => '',
    			'pagos' => array(),
    			'productos' => array());    	    
    	
    	// y lo guardo en sesión
    	$sesion = $this->getRequest()->getSession();
    	$sesion->set('pedido', $pedido);
    	
    	return $this->render('PedidoBundle:Default:new.html.twig',
    				array(
    						'lista' => $lista,
    						'paso' => 1));
    }
    
    /**
     * Acción para el segundo paso del pedido, mostrar la lista de categorias del club
     * @param integer $idClub Id del club
     */
    public function newCategoriasAction($idClub)
    {    	
    	// obtener listado de equipos
    	$em = $this->getDoctrine()->getEntityManager();
    	$club = $em->getRepository('ClubBundle:Club')->findClubById($idClub);
    	
    	if (!$club)
    		throw $this->createNotFoundException('No se ha podido encontrar el club.');    	    	            	    	    	    
    	 
    	return $this->render('PedidoBundle:Default:new.html.twig',
    			array(    					
    					'paso' => 2,
    					'club' => $club));
    }
    
    /**
     * Acción para el tercer paso del pedido, mostrar la lista de galerias del club
     * @param integer $categoria Id de de la categoria
     */
    public function newGaleriasAction($categoria)
    {
    	// obtener listado de equipos
    	$em = $this->getDoctrine()->getEntityManager();
    	//$galerias = $em->getRepository('GaleriaBundle:Galeria')->findGaleriasByIdCategoria($categoria);
    	
    	$categoria = $em->getRepository('ClubBundle:Club')->findCategoriaById($categoria);
    	 
    	if (!$categoria)
    		throw $this->createNotFoundException('No se ha podido encontrar la categoria.');    	     
    
    	return $this->render('PedidoBundle:Default:new.html.twig',
    			array(
    					'categoria' => $categoria,
    					'paso' => 3));
    }
    
    /**
     * Acción para el cuarto paso del pedido, mostrar la lista de fotos de la galeria
     * @param integer $galeria Id de de la galeria
     */
    public function newFotosAction($galeria)
    {    	
    	$em = $this->getDoctrine()->getEntityManager();
		//recupero la informacion de la galeria a mostrar
		$galeria = $em->getRepository('GaleriaBundle:Galeria')->findGaleriaById($galeria);
		if (!$galeria) {
			throw $this->createNotFoundException('No se ha podido encontrar la galería.');
		}		
    
    	return $this->render('PedidoBundle:Default:new.html.twig',
    			array(
    					'galeria' => $galeria,
    					'paso' => 4));
    }
    
    /**
     * Acción para la seleccion de las fotos del pedido     
     */
    public function seleccionFotosAction()
    {
    	// obtengo la informacion de la request
    	$request = $this->getRequest();
    	// cojo el id de la galeria
    	$idGaleria = $request->request->get("galeria_id");
    	     	
    	// busco los ids de las fotos seleccionadas
    	if ($request->request->get("fotos_pedido")) {    		
    		$seleccion = $request->request->get("fotos_pedido");
    		// y lo guardo en sesión
    		$sesion = $this->getRequest()->getSession();
    		$sesion->set('fotos', $seleccion);
    		$sesion->set('galeria', $idGaleria);    		
    		// muestro la primera foto 
    		$em = $this->getDoctrine()->getEntityManager();
    		$galeria = $em->getRepository('GaleriaBundle:Galeria')->findGaleriaById($idGaleria);
    		// inicio el indice
    		$indice = 0;    		
			// recupero la foto 
    		$foto = $em->getRepository('GaleriaBundle:Galeria')->findFotoById(intval($seleccion[0]));
    		// cargo los tipos de productos
    		$tipos = $em->getRepository('PedidoBundle:Pedido')->findAllTiposProducto();
    		return $this->render('PedidoBundle:Default:new.html.twig',
    				array(
    						'foto' => $foto,
    						'categoria' => $galeria->getCategoria(),
    						'galeria' => $galeria,
    						'tipos' => $tipos,
    						'indice' => (count($seleccion) - 1 == $indice) ? null : $indice,
    						'paso' => 5));
    		
    	} else {    	    		    		    
    		// redirijo a la pagina que estaba
    		$this->get('session')->setFlash('notice', 'Sebe seleccionar al menos una foto para el pedido');
    		return $this->redirect($this->generateUrl('pedido_new_fotos', array ('galeria' => $idGaleria)));
    	}      
    }
    
    /**
     * Acción para ir guardando el pedido de cada una de las fotos seleccionada
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function guardarProductoAction () {        	
    	$em = $this->getDoctrine()->getEntityManager();
    	$sesion = $this->getRequest()->getSession();
    	// obtengo la informacion de la request
    	$request = $this->getRequest();
    	// cojo la información de la galeria
    	$idGaleria = intval($sesion->get('galeria'));    	    	
    	$galeria = $em->getRepository('GaleriaBundle:Galeria')->findGaleriaById($idGaleria);
    	// cojo la información del listado de las fotos
    	$seleccion = $sesion->get('fotos');
    	// cojo el indice de la foto que se muestra
    	$indice = 1 + intval($request->request->get("indice_foto"));
    	// si es la primera vez, lo guardo en sesion
    	$foto = $em->getRepository('GaleriaBundle:Galeria')->findFotoById(intval($seleccion[$indice]));
    	// cargo los tipos de productos
    	$tipos = $em->getRepository('PedidoBundle:Pedido')->findAllTiposProducto();    	
    	// añado al pedido
    	$pedido = $sesion->get('pedido');
    	$cantidades = $request->request->get('tipo_cantidad', array());    	    	
    	$fotoId = $request->request->get('fotoId', null);
    	foreach ($cantidades as $key => $valor) {    		    		
    		if (is_numeric($valor)) {    			
    			$producto = array(
    							'pedido' => null,
    							'foto' => $fotoId,
    							'tipo_producto' => $tipos[$key]->getId(),
    							'cantidad' => intval($valor));
    			
    			$pedido['productos'][] = $producto;     			
    		}
    	}  
    	// guardo el pedido en la sesion
    	$sesion->set('pedido', $pedido);    	
    	
    	return $this->render('PedidoBundle:Default:new.html.twig',
    			array(
    					'foto' =>$foto,
    					'categoria' => $galeria->getCategoria(),
    					'galeria' => $galeria,
    					'tipos' => $tipos,
    					'indice' => (count($seleccion) - 1 == $indice) ? null : $indice,
    					'paso' => 5));    
    }
    /**
     * Accion para confirmar el pedido
     */
    public function confirmarAction()
    {
    	$em = $this->getDoctrine()->getEntityManager();
    	$sesion = $this->getRequest()->getSession();
    	// obtengo la informacion de la request
    	$request = $this->getRequest();    	
    	// cargo los tipos de productos
    	$tipos = $em->getRepository('PedidoBundle:Pedido')->findAllTiposProducto();
    	// añado al pedido
    	$pedido = $sesion->get('pedido');
    	$cantidades = $request->request->get('tipo_cantidad', array());
    	$fotoId = $request->request->get('fotoId', null);
    	foreach ($cantidades as $key => $valor) {
    		if (is_numeric($valor)) {
    			$producto = array(
    					'pedido' => null,
    					'foto' => $fotoId,
    					'tipo_producto' => $tipos[$key]->getId(),
    					'cantidad' => intval($valor));
    			 
    			$pedido['productos'][] = $producto;
    		}
    	}

    	$total = 0.00;
    	// cargo los tipos por ID
    	$tipos = $em->getRepository('PedidoBundle:Pedido')->findAllTiposProductoWithKeyId();
    	// calculo el total a pagar    	

src/FotoCuadro/PedidoBundle/Resources/views/Default/confirmar.html.twig
{% extends '::base.html.twig' %}
{% block title %}Pedidos{% endblock %}
{% block stylesheets %}
	{{ parent() }}        	        	        
{% endblock %}

{% block contenido %}
	<div class="contenido">		
		<div class="title">Pedidos</div>				    
		<form action="{{ path('pedido_crear') }}" method="post">  						
			<div class="centro">	
				<!-- Formulario general de un club  -->
				<div class="box_ficha">	
					<div class="sub-title">Cliente</div>																						
					<table width="100%" border="0" cellspacing="0" cellpadding="0">
						<tr>
							<td><strong>{{ form_label(form.nombre) }}</strong></td>
							<td>{{ form_widget(form.nombre, { 'attr': { 'size': '40'} }) }}</td>						 
						</tr>										
						<tr>
							<td><strong>{{ form_label(form.apellidos) }}</strong></td>
							<td>{{ form_widget(form.apellidos) }}</td>
						</tr>
						<tr>
							<td><strong>{{ form_label(form.email) }}</strong></td>
							<td>{{ form_widget(form.email) }}</td>	
						</tr>
						<tr>
							<td><strong>{{ form_label(form.telefono) }}</strong></td>
							<td>{{ form_widget(form.telefono) }}</td>			
						</tr>														
					</table>
					<br /><br />	
					<table width="30%" border="0" cellspacing="0" cellpadding="0">
						<tr>
							<td>TOTAL</td>
							<td>A cuenta</td>
						</tr>
						<tr>
							<td><input type="text" disabled="disabled" value="{{ total }}" size="20"></td>
							<td><input type="text" value="" name="acuenta" value="0" size="20"></td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>A PAGAR</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td><input type="text" disabled="disabled" value="" size="20"></td>
						</tr>
					</table>
					<button type="submit">Terminar</button>
					<button type="button" value="volver" name="volver">Volver</button>
			</div>			
		</form>
				
	</div>							
{% endblock %}
{% block javascripts %}
	{{ parent() }}	
	<script type="text/javascript">
jQuery(document).ready(function() {
	 // Get the div that holds the collection of tags
	var collectionHolder = $('ul.categorias');
	// setup an "add a tag" link
	var $addCategoriaLink = $('<a href="#" class="add_categoria_link">A&ntilde;adir categoria</a>');
	var $newLinkLi = $('<li></li>').append($addCategoriaLink);
	    // add the "add a tag" anchor and li to the tags ul
	    collectionHolder.append($newLinkLi);

	    $addCategoriaLink.on('click', function(e) {	    	
	        // prevent the link from creating a "#" on the URL
	        e.preventDefault();
	        // add a new tag form (see next code block)
	        addCategoriaForm(collectionHolder, $newLinkLi);
	    });
	});

function addCategoriaForm(collectionHolder, $newLinkLi) {
    // Get the data-prototype we explained earlier
    var prototype = collectionHolder.attr('data-prototype');
    // Replace '__name__' in the prototype's HTML to
    // instead be a number based on the current collection's length.
    var newForm = prototype.replace(/\$\$name\$\$/g, collectionHolder.children().length);

    // Display the form in the page in an li, before the "Add a tag" link li
    var $newFormLi = $('<li></li>').append(newForm);
    $newLinkLi.before($newFormLi);

	 // add a delete link to the new form
    addTagFormDeleteLink($newFormLi);
}

function addTagFormDeleteLink($tagFormLi) {
    var $removeFormA = $('<a href="#">Eliminar</a>');
    $tagFormLi.append($removeFormA);

    $removeFormA.on('click', function(e) {
        // prevent the link from creating a "#" on the URL
        e.preventDefault();

        // remove the li for the tag form
        $tagFormLi.remove();
    });
}

$(".del_categoria").click(function(event){
	// prevent the link from creating a "#" on the URL
    event.preventDefault();	
    var answer = confirm('¿Seguro que quieres eliminar la categoría?');
    if(answer){
		var index = $(this).attr("id");	 	     
		$('#li'+index).remove()
    }   					 
});		

</script>	
{% endblock %}

src/FotoCuadro/PedidoBundle/Resources/views/Default/edit.html.twig
{% extends '::base.html.twig' %}
{% block title %}Pedidos{% endblock %}
{% block stylesheets %}
	{{ parent() }}        	        	        
{% endblock %}

{% block contenido %}
	<div class="contenido">		
		<div class="title">Pedidos</div>		
    	{# incluyo la plantilla con el form de edición de un pedido #}
    		<div class="sub-title">Pedido #{{ entity.id }}</div>
    		<div class="sub-title">Fecha: {{ entity.fecha|date("d/m/Y") }}</div>
		<form action="{{ path('pedido_update', {'id' : entity.id}) }}" method="post" >  						
			<div class="izquierda">	
				<!-- Formulario general de un pedido  -->
				<div class="box_ficha">											
												
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<td colspan="2">Comprador</td>
					</tr>
					<tr>
						<td colspan="2"><strong>ID</strong>&nbsp;{{ entity.cliente.id }}</td>												
					</tr>
					<tr>
						<td colspan="2">{{ entity.cliente.nombre ~ ' ' ~ entity.cliente.apellidos }}</td>												
					</tr>
					<tr>
						<td colspan="2">Usuario</td>
					</tr>
					<tr>
						<td colspan="2"><strong>ID</strong>&nbsp;{{ entity.usuario.id }}</td>												
					</tr>
					<tr>
						<td colspan="2">{{ entity.usuario.nombre ~ ' ' ~ entity.usuario.apellidos }}</td>												
					</tr>
					<tr>
						<td colspan="2">Estado</td>												
					</tr>
					<tr>
						<td colspan="2">
							<select name="pedido_estado">
							{% for key, estado in estados %}
								<option value="{{ key }}" {{ key == entity.estado ? 'selected=selected' : '' }}>{{ estado }}</option>
							{% endfor %}
							</select>						
						</td>												
					</tr>
					
					<tr>
						<td>Importe</td>						
						<td>Pagado</td>		
					</tr>		
					<tr>
						<td><input type="text" name="pedido_importe" readonly="readonly" value="{{ entity.importe }}">&nbsp;&euro;</td>
						<td><input type="text" name="pedido_pagado" value="{{ entity.pagado }}">&nbsp;&euro;</td>
					</tr>					
				</table>					 								
				<button type="submit">Aceptar</button>																 	  					   			
				<button type="button" onclick="location.href='{{ path('menu_pedido') }}';" value="volver" name="volver">Volver</button>
			</div>
			<div class="derecha">
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<th>Productos</th>
						<th>Cantidad</th>
					</tr>
					{% for producto in entity.productos %}
						<tr>
							<td>{{ producto.tipoProducto.nombre }} ({{ producto.foto.archivo }})</td>
							<td>{{ producto.cantidad }}</td>
						</tr>
					{% endfor %}
				</table>
			</div>	
		</form>
				
	</div>							
{% endblock %}
{% block javascripts %}
	{{ parent() }}	
	<script type="text/javascript">
jQuery(document).ready(function() {
	 // Get the div that holds the collection of tags
	var collectionHolder = $('ul.categorias');
	// setup an "add a tag" link
	var $addCategoriaLink = $('<a href="#" class="add_categoria_link">A&ntilde;adir categoria</a>');
	var $newLinkLi = $('<li></li>').append($addCategoriaLink);
	    // add the "add a tag" anchor and li to the tags ul
	    collectionHolder.append($newLinkLi);

	    $addCategoriaLink.on('click', function(e) {	    	
	        // prevent the link from creating a "#" on the URL
	        e.preventDefault();
	        // add a new tag form (see next code block)
	        addCategoriaForm(collectionHolder, $newLinkLi);
	    });
	});

function addCategoriaForm(collectionHolder, $newLinkLi) {
    // Get the data-prototype we explained earlier
    var prototype = collectionHolder.attr('data-prototype');
    // Replace '__name__' in the prototype's HTML to
    // instead be a number based on the current collection's length.
    var newForm = prototype.replace(/\$\$name\$\$/g, collectionHolder.children().length);

    // Display the form in the page in an li, before the "Add a tag" link li
    var $newFormLi = $('<li></li>').append(newForm);
    $newLinkLi.before($newFormLi);

	 // add a delete link to the new form
    addTagFormDeleteLink($newFormLi);
}

function addTagFormDeleteLink($tagFormLi) {
    var $removeFormA = $('<a href="#">Eliminar</a>');
    $tagFormLi.append($removeFormA);

    $removeFormA.on('click', function(e) {
        // prevent the link from creating a "#" on the URL
        e.preventDefault();

        // remove the li for the tag form
        $tagFormLi.remove();
    });
}

$(".del_categoria").click(function(event){
	// prevent the link from creating a "#" on the URL
    event.preventDefault();	
    var answer = confirm('¿Seguro que quieres eliminar la categoría?');
    if(answer){
		var index = $(this).attr("id");	 	     
		$('#li'+index).remove()
    }   					 
});		

</script>	
{% endblock %}

src/FotoCuadro/PedidoBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}
{% block title %}Pedidos{% endblock %}
{% block stylesheets %}
	{{ parent() }}        	        	        
{% endblock %}

{% block contenido %}
	<div class="contenido">		
		<div class="title">Pedidos</div>
		<div class="izquierda">	
			{% if pedidos %}			    			
    			{# incluyo la plantilla con el listado de pedidos #}
    			{% include 'PedidoBundle:Default:widget/listado.html.twig' %}
    		{% else %}
    			<p>No hay pedidos para mostrar</p>	    			
    		{% endif %}    		
		</div>
		<div class="derecha">
			<button type="button" class="boton_big" onclick="location.href='{{ path('pedido_new_clubes') }}';" value="realizar_pedido" name="realizar_pedido">Realizar pedido</button>			   	
		</div>
		
	</div>							
{% endblock %}

{% block javascripts %}
	{{ parent() }}		
{% endblock %}

src/FotoCuadro/PedidoBundle/Resources/views/Default/new.html.twig
{% extends '::base.html.twig' %}
{% block title %}Pedidos{% endblock %}
{% block stylesheets %}
	{{ parent() }}        	        	        
{% endblock %}

{% block contenido %}
	<div class="contenido">		
		<div class="title">Pedidos</div>		
    	{% if paso == 1 %}
    		{% include 'PedidoBundle:Default:widget/pedido_clubes.html.twig' %}
    	{% elseif paso == 2 %}
    		{% include 'PedidoBundle:Default:widget/pedido_categorias.html.twig' %}
    	{% elseif paso == 3 %}
    		{% include 'PedidoBundle:Default:widget/pedido_galerias.html.twig' %}
    	{% elseif paso == 4 %}
    		{% include 'PedidoBundle:Default:widget/pedido_fotos.html.twig' %}
    	{% elseif paso == 5 %}
    		{% include 'PedidoBundle:Default:widget/pedido_productos.html.twig' %}
    	{% endif %}
				
	</div>							
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	<script type="text/javascript">
		jQuery(document).ready(function() {
			$('.image-checkbox-container img').live('click', function(){
				alert("asasas");
			    if(!$(this).prev('input[type="checkbox"]').prop('checked')){
			        $(this).prev('input[type="checkbox"]').prop('checked', true).attr('checked','checked');
			        this.style.border = '4px solid #38A';
			        this.style.margin = '0px';
			    }else{
			        $(this).prev('input[type="checkbox"]').prop('checked', false).removeAttr('checked');
			        this.style.border = '0';
			        this.style.margin = '4px';
			    }
			});​	
		});
	</script>	
{% endblock %}